#!/usr/bin/env python3
import math
from PIL import Image

def get_closest_color(r, g, b):
    # تعريف الألوان المرجعية بناءً على صورتك
    colors = {
        "bg": {"rgb": (0, 100, 140), "hex": None},         # الخلفية الزرقاء (ستصبح شفافة)
        "green": {"rgb": (120, 190, 80), "hex": "#27ae60"}, # دول إسلامية > 50%
        "yellow": {"rgb": (255, 200, 0), "hex": "#f1c40f"}, # دول إسلامية 10-50%
        "grey": {"rgb": (130, 130, 130), "hex": "#4a4a4a"}  # باقي العالم (رمادي داكن ليتناسب مع Github)
    }

    min_dist = float('inf')
    closest = None

    # حساب أقرب لون بكسل للون المرجعي
    for name, data in colors.items():
        tr, tg, tb = data["rgb"]
        dist = math.sqrt((r - tr)**2 + (g - tg)**2 + (b - tb)**2)
        if dist < min_dist:
            min_dist = dist
            closest = name

    return closest, colors[closest]["hex"]

def generate_dot_map(image_path, output_path, width_dots=180):
    print(f"Loading image: {image_path}...")
    img = Image.open(image_path).convert('RGB')
    w, h = img.size

    # حساب الأبعاد الجديدة مع الحفاظ على نسبة العرض للارتفاع
    aspect_ratio = h / w
    height_dots = int(width_dots * aspect_ratio)

    print(f"Resizing to grid: {width_dots}x{height_dots} dots...")
    img_resized = img.resize((width_dots, height_dots), Image.Resampling.NEAREST)

    # إعدادات الـ SVG
    dot_radius = 3.5
    spacing = 10
    svg_width = width_dots * spacing
    svg_height = height_dots * spacing

    svg_content = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {svg_width} {svg_height}" width="100%">',
        '  <!-- Generated by Eng. Ahmed Sovereign Workspace -->',
        '  <style>',
        '    circle { transition: all 0.3s ease; }',
        '    circle:hover { r: 6; opacity: 0.8; }', # تأثير تفاعلي عند تمرير الماوس
        '  </style>'
    ]

    dots_count = 0
    for y in range(height_dots ):
        for x in range(width_dots):
            r, g, b = img_resized.getpixel((x, y))
            color_name, hex_code = get_closest_color(r, g, b)

            # تجاهل الخلفية الزرقاء
            if color_name == "bg":
                continue

            cx = x * spacing + (spacing / 2)
            cy = y * spacing + (spacing / 2)

            svg_content.append(f'  <circle cx="{cx}" cy="{cy}" r="{dot_radius}" fill="{hex_code}" />')
            dots_count += 1

    svg_content.append('</svg>')

    with open(output_path, 'w') as f:
        f.write('\n'.join(svg_content))

    print(f"Success! SVG generated with {dots_count} dots.")
    print(f"Saved to: {output_path}")

if __name__ == "__main__":
    # المسارات الدقيقة بناءً على بيئتك
    INPUT_IMAGE = "/home/kubuntu/Desktop/Muslim_world_map-ar-colored.png"
    OUTPUT_SVG = "/home/kubuntu/Desktop/islamic_world_map.svg"

    try:
        generate_dot_map(INPUT_IMAGE, OUTPUT_SVG)
    except FileNotFoundError:
        print(f"Error: Could not find the image '{INPUT_IMAGE}'. Please check the path.")
